### PR TITLE
BUGFIX: MPNT-60 Demo data source PDM missing geo__state__location column

### PR DESCRIPTION
**Pull request by huavannis**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/30/ : FAILURE in 9s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/52/ : SUCCESS in 6s

**Comment by huavannis** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/31/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/53/ : SUCCESS in 7s

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gdc-public-demos-gate-PR17

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-fossa-scanning-zuul-el7/16/ : SUCCESS in 56s (non-voting)
- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/32/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-sonarqube-scan-zuul-gate/16/ : SUCCESS in 25s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-merge-compliance-check/17/ : SUCCESS in 21s

**Pull request merged**
