### PR TITLE
MPNT-26 - update csv files with geo data

### PR DESCRIPTION
**Pull request by tvthuan210**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/12/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/36/ : SUCCESS in 6s

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gdc-public-demos-gate-PR15

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-fossa-scanning-zuul-el7/14/ : SUCCESS in 1m 13s (non-voting)
- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/13/ : FAILURE in 8s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-sonarqube-scan-zuul-gate/14/ : SUCCESS in 41s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-merge-compliance-check/15/ : SUCCESS in 26s

**Comment by danh-ung** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/14/ : FAILURE in 7s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/37/ : SUCCESS in 6s

**Comment by phong-nguyen-duy** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/15/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/38/ : SUCCESS in 6s

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gdc-public-demos-gate-PR15

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-fossa-scanning-zuul-el7/15/ : SUCCESS in 1m 08s (non-voting)
- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/16/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-sonarqube-scan-zuul-gate/15/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-merge-compliance-check/16/ : SUCCESS in 23s

**Pull request merged**
