### PR TITLE
README.md Update

### PR DESCRIPTION
**Pull request by sheilajung**
initial test

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/1/ : SUCCESS in 9s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gdc-public-demos-fossa-scanning-zuul-el7 : SKIPPED (non-voting)
- gdc-public-demos-sonarqube-scan-zuul-gate : SKIPPED
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-merge-compliance-check/1/ : FAILURE in 17s

**Comment by nathanmpark** [comment]
lgtm

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gdc-public-demos-gate-PR1

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-fossa-scanning-zuul-el7/1/ : SUCCESS in 33s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-sonarqube-scan-zuul-gate/1/ : SUCCESS in 20s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-merge-compliance-check/2/ : SUCCESS in 19s

**Pull request merged**
