### PR TITLE
MPNT-58 - rename demo database and workspace

### PR DESCRIPTION
**Pull request by tvthuan210**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/40/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/59/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/41/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/60/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/42/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/61/ : SUCCESS in 6s

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gdc-public-demos-gate-PR20

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-fossa-scanning-zuul-el7/19/ : SUCCESS in 1m 44s (non-voting)
- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/43/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-sonarqube-scan-zuul-gate/19/ : SUCCESS in 41s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-merge-compliance-check/20/ : SUCCESS in 22s

**Pull request merged**
