### PR TITLE
test validation

### PR DESCRIPTION
**Pull request by phong-nguyen-duy**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/1/ : FAILURE in 10s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/26/ : SUCCESS in 10s

**Comment by phong-nguyen-duy** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/2/ : FAILURE in 9s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/27/ : SUCCESS in 9s

**Comment by ngocmanhha** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/3/ : FAILURE in 8s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/28/ : SUCCESS in 8s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/4/ : FAILURE in 6s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/29/ : SUCCESS in 7s

**Comment by ngocmanhha** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/5/ : FAILURE in 20s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/30/ : SUCCESS in 9s

**Comment by ngocmanhha** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/7/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/31/ : SUCCESS in 7s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/9/ : FAILURE in 18s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/33/ : SUCCESS in 12s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/10/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/34/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/11/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/35/ : SUCCESS in 6s

**Comment by phong-nguyen-duy** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/17/ : SUCCESS in 24s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/39/ : SUCCESS in 8s

**Comment by phong-nguyen-duy** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/18/ : FAILURE in 16s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/40/ : SUCCESS in 16s

**Comment by phong-nguyen-duy** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/19/ : FAILURE in 16s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/41/ : SUCCESS in 9s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/gdc-public-demos/job/gdc-public-demos-validation/20/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/compliance/job/gdc-public-demos-oss-check/42/ : SUCCESS in 9s

**Pull request closed without merging**
